
export const BrowseActionTypes = {
	CHANGE_MILEAGE_VALUE: 'CHANGE_MILEAGE_VALUE',
	CHANGE_PRICE_VALUE: 'CHANGE_PRICE_VALUE',
	GET_BROWSEDATA:'GET_BROWSEDATA',
	GET_DETAILDATA:'GET_DETAILDATA',
	GET_SEARCHDATA:'GET_SEARCHDATA',
}