export const HomeActionTypes = {
	GET_CATEGORIES: 'GET_CATEGORIES',
	GET_BRANDS: 'GET_BRANDS',
	GET_RECENT_CARS: 'GET_RECENT_CARS',
	GET_TOPOFFERS: 'GET_TOPOFFERS',
	GET_LATESTNEWS: 'GET_LATESTNEWS',
	GET_REVIEWS: 'GET_REVIEWS',
}