
export const ProfileActionTypes = {
	CHANGE_COMPONENT_ACTIVE: 'CHANGE_COMPONENT_ACTIVE',
	FETCH_USER_INFO: 'FETCH_USER_INFO',
	UPDATE_PROFILE: 'UPDATE_PROFILE',
	CHATTING : 'CHATTING',
	UPDATE_PASSWORD: 'UPDATE_PASSWORD',
	FETCH_MESSAGES: 'FETCH_MESSAGES',
	FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
}